# Identificador único (debe coincidir con el que creaste en la web)
sonar.projectKey=Acamdey-test
sonar.projectName=Academy Test Backend
# Versión del proyecto
sonar.projectVersion=1.0

# Qué carpetas escanear (el código fuente)
sonar.sources=src

# Qué carpetas ignorar (test, node_modules, dist)
sonar.exclusions=**/node_modules/**,**/dist/**,**/*.spec.ts,**/*.test.ts

# Idioma (opcional, pero ayuda)
sonar.language=ts
sonar.sourceEncoding=UTF-8